var grids=["  HS2AA HS2AE HS2BB HS2BF".split(" "),"  HS2AB HS2AF HS2BC HS2BG".split(" "),"  HS2AC HS2AG HS2BD HS2CA".split(" "),"  HS2AD HS2BA HS2BE HS2CB".split(" ")],Invalid="Invalid Ref",MapSize=700;function padzero(a){10>a&&(a="0"+a);return a}
function latlon2text(a,b){hemlon="E";0>b&&(hemlon="W");hemlat="N";0>a&&(hemlat="S");a=Math.abs(a);b=Math.abs(b);deglat=parseInt(a);deglon=parseInt(b);a=60*(a-deglat);b=60*(b-deglon);minlat=parseInt(a);minlon=parseInt(b);return padzero(deglat)+"&deg;"+padzero(minlat)+"'"+hemlat+" "+padzero(deglon)+"&deg;"+padzero(minlon)+"'"+hemlon}function validateGR(a){return 11<a.length||5>a.length||0==a.length%2||"HS2"!=a.substring(0,3)?0:a.substring(0,5)}
function GridRef2coord(a,b){if(0==a.length)return 0;var c=check4quadrant(a);if(2==a.length){if("E"==b)return 1E4*a[0];if("N"==b)return 1E4*a[1]}else if(4==a.length){if(c)return"E"==b?"SW"==c||"NW"==c?1E4*a[0]+0:1E4*a[0]+5E3:"SW"==c||"SE"==c?1E4*a[1]+0:1E4*a[1]+5E3;if("E"==b)return 1E4*a[0]+1E3*a[1];if("N"==b)return 1E4*a[2]+1E3*a[3]}else if(6==a.length){if(c)return"E"==b?"SW"==c||"NW"==c?1E4*a[0]+1E3*a[1]+0:1E4*a[0]+1E3*a[1]+500:"SW"==c||"SE"==c?1E4*a[2]+1E3*a[3]+0:1E4*a[2]+1E3*a[3]+500;if("E"==b)return 1E4*
a[0]+1E3*a[1]+100*a[2];if("N"==b)return 1E4*a[3]+1E3*a[4]+100*a[5]}return Invalid}function GridRef2Easting(a){var b=validateGR(a);if(!b)return Invalid;var c=Invalid;for(i=0;i<grids.length;i++)for(j=0;j<grids[i].length;j++)if(grids[i][j]==b){c=1E5*i;break}if(c!=Invalid){a=GridRef2coord(a.substring(5),"E");if(a==Invalid)return a;c+=a}return c}
function GridRef2Northing(a){var b=validateGR(a);if(!b)return Invalid;var c=Invalid;for(i=0;i<grids.length;i++)for(j=0;j<grids[i].length;j++)if(grids[i][j]==b){c=1E5*j;break}if(c!=Invalid){a=GridRef2coord(a.substring(5),"N");if(a==Invalid)return a;c+=a}return c}function ord2index(a){var b=[0,0,0,0,0,0];a=Math.floor(a);for(var c=0;6>c;)b[c]=Math.floor(a/Math.pow(10,5-c)),a-=b[c]*Math.pow(10,5-c),c++;return b}
function check4quadrant(a){a=a.substring(a.length-2,a.length);return"SW"==a||"NW"==a||"NE"==a||"SE"==a?a:0}function quadrant(a,b){return 5>a&&5>b?"SW":5>a&&5<=b?"NW":5<=a&&5>b?"SE":5<=a&&5<=b?"NE":""}
function coords2GridRef(a,b,c){if(0>a||4E5<=a)return"Invalid Easting";if(2E5>b||6E5<=b)return"Invalid Northing";a=ord2index(a);var d=ord2index(b);b=grids[a[0]][d[0]];10==c?b+=String(a[1])+String(d[1]):5==c?b+=String(a[1])+String(d[1])+quadrant(a[2],d[2]):1==c?b+=String(a[1])+String(a[2])+String(d[1])+String(d[2]):.5==c?b+=String(a[1])+String(a[2])+String(d[1])+String(d[2])+quadrant(a[3],d[3]):.1==c&&(b+=String(a[1])+String(a[2])+String(a[3])+String(d[1])+String(d[2])+String(d[3]));return b}
function getImageCoords(a,b){var c=a.offsetX-b.offsetLeft,d=a.offsetY-b.offsetTop;c=c/b.width*4E5;d=6E5-d/b.height*4E5;coordinates.innerHTML=Math.floor(c)+"E,"+Math.floor(d)+"N"}function showCoords(a,b){var c=a.offsetX-b.offsetLeft,d=a.offsetY-b.offsetTop;c=c/b.width*4E5;d=6E5-d/b.height*4E5;Easting.value=Math.round(c);Northing.value=Math.round(d);toGrid()}
function updateMarker(a,b){var c=a/4E5*MapSize,d=(6E5-b)/4E5*MapSize;c<=MapSize&&d<=MapSize?(document.getElementById("overlay").style.left=c-8+"px",document.getElementById("overlay").style.top=d-8+"px",document.getElementById("overlay").style.display="block"):document.getElementById("overlay").style.display="none"}
function toGrid(){var a=Easting.value,b=Northing.value;updateMarker(a,b);GR100.innerHTML=coords2GridRef(a,b,100);GR10.innerHTML=coords2GridRef(a,b,10);GR5.innerHTML=coords2GridRef(a,b,5);GR1.innerHTML=coords2GridRef(a,b,1);GRp5.innerHTML=coords2GridRef(a,b,.5);GRp1.innerHTML=coords2GridRef(a,b,.1)}
function fromGrid(){var a=GridReference.value,b=GridRef2Easting(a.toUpperCase());a=GridRef2Northing(a.toUpperCase());b!=Invalid&&a!=Invalid?updateMarker(b,a):updateMarker(0,0);EastingResult.value=b;NorthingResult.value=a};

